spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: volume-service
          uri: lb://volume-service
          predicates:
            - Path=/volume/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: container-service
          uri: lb://container-service
          predicates:
            - Path=/container/**
          filters:
            - StripPrefix=1
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/image/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eurekaserver:8070/eureka/
