version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: password
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"
    networks:
      - spring-boot-network

  gatewayapi:
    image: gatewayapi:latest
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - eurekaserver

  configserver:
    image: configserver:latest
    ports:
      - "8089:8089"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      SERVER_PORT: "8089"
    networks:
      - spring-boot-network

  user-services:
    image: user-services:latest
    build:
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:8089"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
      - configserver

  payment-service:
    image: payment-service:latest
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:8089"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
      - configserver

  transaction-service:
    image: transaction-service:latest
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:8089"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
      - configserver

  image-service:
    image: image-service:latest
    build:
      context: ./image-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:8089"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
      - configserver
  
  container-service:
    image: container-service:latest
    build:
      context: ./container-service
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:8089"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
      - configserver

  volume-service:
    image: volume-service:latest
    build:
      context: ./volume-service
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:8089"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
      - configserver

  eurekaserver:
    image: eurekaserver:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      - spring-boot-network

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: dockerdb
      DB_USER: dockeruser
      DB_PASSWORD: password
    ports:
      - "8081:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres


networks:
  spring-boot-network:
    driver: bridge
