server.port=8761
spring.datasource.url=jdbc\:postgresql\://postgres\:5432/dockerdb
spring.datasource.username=dockeruser
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

spring.application.name=eureka-server
spring.cloud.config.uri=http://configserver:8071
spring.config.import=optional:configserver:http://configserver:8071